### ISSUE TITLE
Please make a proper 0.0.1 release

### ISSUE THREAD

**Issue by siko1056** [aumpierre-unb/Internal-Fluid-Flow-for-GNU-Octave#2]
Hello @aumpierre-unb ,

Studying your repo, I found you uploaded the release tarball `internal_fluid_flow_0_0_1.tar.gz` into the git repository itself.  This is a little odd, since you now maintain an archive of your code into your code (recursive and redundant code storage).

I suggest you remove `internal_fluid_flow_0_0_1.tar.gz` from this repository and instead create a GitHub release https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release. This is quickly done an we can use this release very nicely on Octave Packages.

Thank you for your time and effort,

Kai

**Comment by aumpierre-unb** [comment]
Hi,
.tar.gz file removed, version v0.0.1 released. I presume no actions was intended on the .yaml file.

**Comment by siko1056** [comment]
The yaml part I help out for the start.  The maintenance of new releases you can do as you wish later.
